# Generated by Django 4.2.6 on 2024-06-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdetailes",
            name="blood",
        ),
        migrations.AddField(
            model_name="userdetailes",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
