# Generated by Django 5.0.6 on 2024-07-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_remove_userdetailes_blood_userdetailes_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetailes",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
