# Generated by Django 5.0.6 on 2024-06-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieinfo",
            name="director",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="movieinfo",
            name="title",
            field=models.CharField(max_length=250),
        ),
    ]
